volumes:
  neo4j-data:
    driver: local

services:
  neo4j:
    build: .
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.export.file.enabled=true
      - NEO4J_server_memory_heap_max__size=5GB